spring:
  application:
    name: api-gateway

  # OAuth2 Resource Server used JWT from Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm  # Realm Keycloak xác thực JWT

  # Spring Cloud Gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Authentication-service route
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        # Post-service route
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/posts/**
        # Amenity-service route
        - id: amenity-service
          uri: lb://amenity-service
          predicates:
            - Path=/api/v1/amenities
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/v1/search
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**

# Micrometer Tracing + Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Địa chỉ của Eureka Server
    fetch-registry: true  # Bật lấy danh sách các service khác từ Eureka
    register-with-eureka: true  # Cho phép đăng ký service này với Eureka

# logging
logging:
  level:
    org.example.authservice.controller: INFO
    org.springframework.web.client.RestTemplate: INFO
    org.springframework.security: DEBUG
    brave: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    zipkin2.reporter: DEBUG
    org.springframework.cloud.gateway: DEBUG
