spring:
  application:
     name: ai-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
server:
  port: 8086

gemini:
  api-key: AIzaSyBfEMq96WbVkFk8v3Zrnrbg47T0PUExTkY

# Register Eureka Server
eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    export:
      prometheus:
        enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
    reactor.netty.http.client: INFO
    reactor.netty: INFO
    root: INFO
    org.springframework.web: DEBUG
    org.example.aiservice: DEBUG
    okhttp3: DEBUG
    okhttp3.internal.http: DEBUG
