server:
  port: 8086

elasticsearch:
  host: localhost
spring:
  application:
    name: search-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.commonevent.common.event"
        spring.json.type.mapping: CreatePostDocumentEvent:org.example.commonevent.common.event.CreatePostDocumentEvent
      group-id: searchGroup
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Logging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
    reactor.netty.http.client: INFO
    reactor.netty: INFO
