server:
  port: 8083

spring:
  application:
    name: amenity-service
  datasource:
    url: jdbc:postgresql://localhost:5001/amenity-service
    username: postgres
    password: lam1782004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.example.authservice.controller: INFO
    org.springframework.security: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
    reactor.netty.http.client: INFO
    reactor.netty: INFO
    brave: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    zipkin2.reporter: DEBUG