spring:
  application:
    name: api-gateway

  # OAuth2 Resource Server used JWT from Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm  # Realm Keycloak xác thực JWT

  # Spring Cloud Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

# Micrometer Tracing + Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    export:
      prometheus:
        enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Địa chỉ của Eureka Server
    fetch-registry: true  # Bật lấy danh sách các service khác từ Eureka
    register-with-eureka: true  # Cho phép đăng ký service này với Eureka

# logging
logging:
  level:
    org.example.authservice.controller: INFO
    org.springframework.web.client.RestTemplate: INFO
    org.springframework.security: DEBUG
    brave: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    zipkin2.reporter: DEBUG